.TH "/scratch1/NCEPDEV/nems/Denise.Worthen/WORK/utils_dw/sorc/regrid_sfc.fd/regridStates.F90" 3 "Wed May 14 2025" "Version 1.13.0" "regrid_sfc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/nems/Denise.Worthen/WORK/utils_dw/sorc/regrid_sfc.fd/regridStates.F90 \- Program to re-grid a list of FV3 variables\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBregridstates\fP"
.br
.RI "Program to re-grid a list of FV3 variables\&. "
.in -1c
.SH "Detailed Description"
.PP 
Program to re-grid a list of FV3 variables\&. 


.PP
\fBAuthor:\fP
.RS 4
Clara Draper, and George Gayno Aug, 2024\&. 
.RE
.PP

.PP
Definition in file \fBregridStates\&.F90\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "program regridstates ()"

.PP
Program to re-grid a list of FV3 variables\&. Intended for use in DA applications (regridding of restarts for recentering, regridding increments)\&. 
.PP
\fBReturns:\fP
.RS 4
0 for success, error code otherwise\&. 
.RE
.PP

.PP
Definition at line 9 of file regridStates\&.F90\&.
.PP
References readin_setup()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for regrid_sfc from the source code\&.
