.TH "md__scratch1_NCEPDEV_nems_Denise.Worthen_WORK_addoitest_sorc_vcoord_gen.fd_docs_README" 3 "Thu May 9 2024" "Version 1.13.0" "vcoord_gen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__scratch1_NCEPDEV_nems_Denise.Worthen_WORK_addoitest_sorc_vcoord_gen.fd_docs_README \- README 
This program generates the parameters needed to define the forecast model's hybrid levels\&.
.PP
Documentation may be found at https://ufs-community.github.io/UFS_UTILS 
