.TH "/scratch1/NCEPDEV/nems/Denise.Worthen/WORK/utils_dw/sorc/ocnice_prep.fd/ocniceprep.F90" 3 "Mon May 6 2024" "Version 1.13.0" "ocnice_prep" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/nems/Denise.Worthen/WORK/utils_dw/sorc/ocnice_prep.fd/ocniceprep.F90 \- Generate warmstart files for ocean or ice by mapping a restart file from 1/4deg to a desired tripole resolution\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBocniceprep\fP"
.br
.RI "Blah blah\&. "
.in -1c
.SH "Detailed Description"
.PP 
Generate warmstart files for ocean or ice by mapping a restart file from 1/4deg to a desired tripole resolution\&. 


.PP
\fBAuthor:\fP
.RS 4
Denise.Worthen@noaa.gov 
.RE
.PP

.PP
Definition in file \fBocniceprep\&.F90\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "program ocniceprep ()"

.PP
Blah blah\&. 
.PP
\fBAuthor:\fP
.RS 4
Denise.Worthen@noaa.gov 
.RE
.PP
\fBReturns:\fP
.RS 4
0 for success, error code otherwise\&. 
.RE
.PP

.PP
Definition at line 12 of file ocniceprep\&.F90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ocnice_prep from the source code\&.
