orog_mask_tools: io_utils Module Reference
io_utils Module Reference
Module containing utilities that read and write data.
Functions/Subroutines
subroutine netcdf_err (err, string)
Check NetCDF error code and output the error message.
subroutine, public qc_orog_by_ramp (imn, jmn, zavg, zslm)
Quality control the global orography and landmask data over Antarctica using RAMP data.
subroutine, public read_global_mask (imn, jmn, mask)
Read input global 30-arc second land mask data.
subroutine, public read_global_orog (imn, jmn, glob)
Read input global 30-arc second orography data.
subroutine, public read_mask (merge_file, slm, land_frac, lake_frac, im, jm)
Read the land mask file.
subroutine, public read_mdl_dims (mdl_grid_file, im, jm)
Read the grid dimensions from the model 'grid' file.
subroutine, public read_mdl_grid_file (mdl_grid_file, im, jm, geolon, geolon_c, geolat, geolat_c, dx, dy, is_north_pole, is_south_pole)
Read the grid dimensions from the model 'grid' file.
subroutine, public write_mask_netcdf (im, jm, slm, land_frac, ntiles, tile, geolon, geolat)
Write the land mask file.
subroutine, public write_netcdf (im, jm, slm, land_frac, oro, hprime, ntiles, tile, geolon, geolat, lon, lat)
Write out orography file in netcdf format.
Detailed Description
Module containing utilities that read and write data.
Author
George Gayno NOAA/EMC
Function/Subroutine Documentation
netcdf_err()
subroutine io_utils::netcdf_err (integer, intent(in) err, character(len=*), intent(in) string) private
Check NetCDF error code and output the error message.
Parameters
[in] err NetCDF error code
[in] string The NetCDF error message
Author
Jordan Alpert NOAA/EMC
Definition at line 239 of file io_utils.F90.
Referenced by qc_orog_by_ramp(), read_global_mask(), read_global_orog(), read_mask(), read_mdl_dims(), read_mdl_grid_file(), write_mask_netcdf(), and write_netcdf().
qc_orog_by_ramp()
subroutine, public io_utils::qc_orog_by_ramp (integer, intent(in) imn, integer, intent(in) jmn, integer, dimension(imn,jmn), intent(inout) zavg, integer, dimension(imn,jmn), intent(inout) zslm)
Quality control the global orography and landmask data over Antarctica using RAMP data.
Parameters
[in] imn i-dimension of the global data.
[in] jmn j-dimension of the global data.
[in,out] zavg The global orography data.
[in,out] zslm The global landmask data.
Author
G. Gayno
Definition at line 628 of file io_utils.F90.
References netcdf_err().
Referenced by tersub().
read_global_mask()
subroutine, public io_utils::read_global_mask (integer, intent(in) imn, integer, intent(in) jmn, integer(1), dimension(imn,jmn), intent(out) mask)
Read input global 30-arc second land mask data.
Parameters
[in] imn i-dimension of orography data.
[in] jmn j-dimension of orography data.
[out] mask The land mask data.
Author
G. Gayno NOAA/EMC
Definition at line 590 of file io_utils.F90.
References netcdf_err(), and orog_utils::transpose_mask().
Referenced by tersub().
read_global_orog()
subroutine, public io_utils::read_global_orog (integer, intent(in) imn, integer, intent(in) jmn, integer*2, dimension(imn,jmn), intent(out) glob)
Read input global 30-arc second orography data.
Parameters
[in] imn i-dimension of orography data.
[in] jmn j-dimension of orography data.
[out] glob The orography data.
Author
Jordan Alpert NOAA/EMC
Definition at line 551 of file io_utils.F90.
References netcdf_err(), and orog_utils::transpose_orog().
Referenced by tersub().
read_mask()
subroutine, public io_utils::read_mask (character(len=*), intent(in) merge_file, real, dimension(im,jm), intent(out) slm, real, dimension(im,jm), intent(out) land_frac, real, dimension(im,jm), intent(out) lake_frac, integer, intent(in) im, integer, intent(in) jm)
Read the land mask file.
Parameters
[in] merge_file path
[in] slm Land-sea mask.
[in] land_frac Land fraction.
[in] lake_frac Lake fraction
[in] im 'i' dimension of a model grid tile.
[in] jm 'j' dimension of a model grid tile.
Author
George Gayno NOAA/EMC
Definition at line 354 of file io_utils.F90.
References lake_frac(), and netcdf_err().
Referenced by tersub().
read_mdl_dims()
subroutine, public io_utils::read_mdl_dims (character(len=*), intent(in) mdl_grid_file, integer, intent(out) im, integer, intent(out) jm)
Read the grid dimensions from the model 'grid' file.
Parameters
[in] mdl_grid_file path/name of model 'grid' file.
[out] im 'i' dimension of a model grid tile.
[out] jm 'j' dimension of a model grid tile.
Author
George Gayno NOAA/EMC
Definition at line 400 of file io_utils.F90.
References netcdf_err().
Referenced by __mtnlm7_oclsm.f90__().
read_mdl_grid_file()
subroutine, public io_utils::read_mdl_grid_file (character(len=*), intent(in) mdl_grid_file, integer, intent(in) im, integer, intent(in) jm, real, dimension(im,jm), intent(out) geolon, real, dimension(im+1,jm+1), intent(out) geolon_c, real, dimension(im,jm), intent(out) geolat, real, dimension(im+1,jm+1), intent(out) geolat_c, real, dimension(im,jm), intent(out) dx, real, dimension(im,jm), intent(out) dy, logical, dimension(im,jm), intent(out) is_north_pole, logical, dimension(im,jm), intent(out) is_south_pole)
Read the grid dimensions from the model 'grid' file.
Parameters
[in] mdl_grid_file Path/name of model 'grid' file.
[in] im 'i' Dimension of a model grid tile.
[in] jm 'j' Dimension of a model grid tile.
[out] geolon Longitude at the grid point centers.
[out] geolon_c Longitude at the grid point corners.
[out] geolat Latitude at the grid point centers.
[out] geolat_c Latitude at the grid point corners.
[out] dx Length of model grid points in the 'x' direction.
[out] dy Length of model grid points in the 'y' direction.
[out] is_north_pole 'true' for points surrounding the north pole.
[out] is_south_pole 'true' for points surrounding the south pole.
Author
George Gayno NOAA/EMC
Definition at line 453 of file io_utils.F90.
References orog_utils::find_nearest_pole_points(), orog_utils::find_poles(), and netcdf_err().
Referenced by tersub().
write_mask_netcdf()
subroutine, public io_utils::write_mask_netcdf (integer, intent(in) im, integer, intent(in) jm, real, dimension(im,jm), intent(in) slm, real, dimension(im,jm), intent(in) land_frac, integer, intent(in) ntiles, integer, intent(in) tile, real, dimension(im,jm), intent(in) geolon, real, dimension(im,jm), intent(in) geolat)
Write the land mask file.
Parameters
[in] im 'i' dimension of a model grid tile.
[in] jm 'j' dimension of a model grid tile.
[in] slm Land-sea mask.
[in] land_frac Land fraction.
[in] ntiles Number of tiles to output.
[in] tile Tile number to output.
[in] geolon Longitude on the model grid tile.
[in] geolat Latitude on the model grid tile.
Author
George Gayno NOAA/EMC
Definition at line 265 of file io_utils.F90.
References netcdf_err().
Referenced by tersub().
write_netcdf()
subroutine, public io_utils::write_netcdf (integer, intent(in) im, integer, intent(in) jm, real, dimension(im,jm), intent(in) slm, real, dimension(im,jm), intent(in) land_frac, real, dimension(im,jm), intent(in) oro, real, dimension(im,jm,14), intent(in) hprime, integer, intent(in) ntiles, integer, intent(in) tile, real, dimension(im,jm), intent(in) geolon, real, dimension(im,jm), intent(in) geolat, real, dimension(im), intent(in) lon, real, dimension(jm), intent(in) lat)
Write out orography file in netcdf format.
Parameters
[in] im 'i' dimension of a model grid tile.
[in] jm 'j' dimension of a model grid tile.
[in] slm Land-sea mask.
[in] land_frac Land fraction.
[in] oro Orography
[in] hprime The gravity wave drag fields on the model grid tile.
[in] ntiles Number of tiles to output.
[in] tile Tile number to output.
[in] geolon Longitude on the model grid tile.
[in] geolat Latitude on the model grid tile.
[in] lon Longitude of the first row of the model grid tile.
[in] lat Latitude of the first column of the model grid tile.
Author
Jordan Alpert NOAA/EMC GFDL Programmer
Definition at line 42 of file io_utils.F90.
References netcdf_err().
Referenced by tersub().