.TH "/scratch1/NCEPDEV/nems/Denise.Worthen/WORK/utils_dw/sorc/gblevents.fd Directory Reference" 3 "Mon Mar 18 2024" "Version 1.13.0" "gblevents" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/nems/Denise.Worthen/WORK/utils_dw/sorc/gblevents.fd Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgblevents\&.f\fP"
.br
.RI "\fIPre/Post processing of of prepbufr events\&. \fP"
.in -1c
